#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.component
Version  : 4.4.0
Release  : 4
URL      : https://pypi.debian.net/zope.component/zope.component-4.4.0.tar.gz
Source0  : https://pypi.debian.net/zope.component/zope.component-4.4.0.tar.gz
Summary  : Zope Component Architecture
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.component-legacypython
Requires: zope.component-python3
Requires: zope.component-python
Requires: Sphinx
Requires: setuptools
Requires: zope.event
Requires: zope.hookable
Requires: zope.interface
BuildRequires : component-python
BuildRequires : pbr
BuildRequires : persistent-python
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : zope.configuration-python
BuildRequires : zope.event
BuildRequires : zope.exceptions-python
BuildRequires : zope.hookable
BuildRequires : zope.i18nmessageid-python
BuildRequires : zope.interface
BuildRequires : zope.location-python
BuildRequires : zope.proxy-python
BuildRequires : zope.schema-python
BuildRequires : zope.security-python
BuildRequires : zope.testing-python

%description
==================

%package legacypython
Summary: legacypython components for the zope.component package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the zope.component package.


%package python
Summary: python components for the zope.component package.
Group: Default
Requires: zope.component-legacypython
Requires: zope.component-python3

%description python
python components for the zope.component package.


%package python3
Summary: python3 components for the zope.component package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zope.component package.


%prep
%setup -q -n zope.component-4.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1512081592
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :
%install
export SOURCE_DATE_EPOCH=1512081592
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
